language: python
cache: pip
sudo: false
python:
  - 3.5
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script: make coverage
after_script: codeclimate-test-reporter
